# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField()),
            ],
        ),
    ]
