# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksearch',
            name='articleHTML',
            field=models.TextField(default='html should be here'),
        ),
        migrations.AddField(
            model_name='stocksearch',
            name='dateCrawled',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
