# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSite', '0002_auto_20171114_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksearch',
            name='stockTicker',
            field=models.TextField(default='XXXX', max_length=5),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='postDate',
            field=models.DateTimeField(),
        ),
    ]
