# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSite', '0003_auto_20180211_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloombergStockSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField()),
                ('dateCrawled', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('articleHTML', models.TextField(default='html should be here')),
                ('stockTicker', models.TextField(default='XXXX', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='cnbcStockSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField()),
                ('dateCrawled', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('articleHTML', models.TextField(default='html should be here')),
                ('stockTicker', models.TextField(default='XXXX', max_length=5)),
            ],
        ),
    ]
