# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-05 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSite', '0004_bloombergstocksearch_cnbcstocksearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_stock_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=5)),
                ('sector', models.CharField(max_length=30, null=True)),
                ('industry', models.CharField(max_length=50, null=True)),
                ('marketCap', models.BigIntegerField()),
            ],
        ),
    ]
