# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockSite', '0005_all_stock_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloombergstocksearch',
            name='sentiment',
            field=models.TextField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='cnbcstocksearch',
            name='sentiment',
            field=models.TextField(default='unknown', max_length=20),
        ),
    ]
