import pickle

article1=["People pass by the Toys R Us store at Times Square in New York, March 9, 2018.The rise and fall of Toys R Us  The toy emporium that Charles P. Lazarus envisioned has been reduced to dusty floors and empty shelves. Much has been said about the demise of the toy empire, which this week announced its plan to liquidate. There have been fingers pointed at corporate raiders, Amazon and big-box stores. All contributed to its undoing. Ultimately, though, Toys R Us' collapse is a story of loyalty run dry. The store in its early days fostered devotion from customers and toymakers. In the end, it lost hold on both. Toys R Us' status as the most important toy store in town left it cavalier, if cocky at times, according to conversations with former employees, executives and industry insiders, who spoke to CNBC on the condition of anonymity. It didn't invest in its stores, even as it was adding to the fleet, leaving it vulnerable when new competition moved in. The story begins with"]

article2=["Microsoft shipped its first video game in 1981, appropriately named Microsoft Adventure. It was an MS-DOS game that booted directly from a floppy disk, and set the stage for Microsoft's adventures in gaming. A lot has changed over the past 37 years, and when you think of Microsoft's efforts in gaming these days you'll immediately think of Xbox. It's fair to say a lot is about to change over the next few decades too, and Microsoft is getting ready. Today, the software giant is unveiling a new gaming cloud division that's ready for a future where consoles and gaming itself are very different to today. Microsoft has been building up to this move for a while. The company has been mysteriously acquiring gaming-related companies over the past few years. From Havok in 2015, Simplygon in 2017, to PlayFab earlier this year, you've probably never heard of any of them, but they're important for Microsoft's bold cloud gaming ambitions. While these acquisitions have been taking place"]

article3=["We believe there is going to be 2 billion gamers in the world, and our goal is to reach every one of them explains Choudhry. Part of the way Microsoft will get there with its new gaming cloud focus is with subscription services. Xbox Game Pass has been available over the past year, and recently Microsoft decided all of its first-party games would come to the subscription service at launch. Sea of Thieves is the first big title, but future Halo and Gears of War games will also be available. We're really pleased with the success that's happening [with Game Pass] says Choudhry. We continue to believe in user choice, and we also believe there's room in the industry for a gaming subscription and that's what we're going to build."]

article4=["ANG stocks have been exploding lately, even as the stock market as a whole has struggled to recoup losses from earlier in the year. FANG, an acronym coined years ago by TheStreet's Jim Cramer, encompasses Facebook Inc. (FB) , Amazon.com Inc. (AMZN) , Netflix Inc. (NFLX) and Alphabet Inc. (GOOGL) . While those stocks have performed with impressive strength in recent history, tech sector gains aren't limited to just FANG. The New York Stock Exchange's FANG Index includes the aforementioned FANG names, plus other heavy hitters Apple Inc. (AAPL) , Twitter Inc. (TWTR) , Baidu IncTesla . That index has climbed 23 so far this year, earning the group of stocks an annualized return of 67 since early last year. The group has even now outpaced the gains of the tech-heavy Nasdaq Composite benchmark index in its final two years of the dot-com bubble, according to Bloomberg data. During the last two years of that rally, the Nasdaq gained 66 outperformed the broader market "]

with open('pickledModel_one.pkl', 'rb') as fin:
  vectorizer, model1 = pickle.load(fin)

X_new=vectorizer.transform(article4)
result1=model1.predict(X_new)

print result1[0]
print type(result1)
